const categories={technology:"开发技术",ai:"人工智能","career-work":"职场工作","finance-business":"金融商业",life:"生活","society-culture":"社会人文","productivity-tools":"效率工具",uncategorized:"暂未分类"};
const types={"web-html":"HTML 网页","web-mhtml":"MHTML 网页","video-page":"视频页面","search-page":"搜索页面","ai-chat":"AI 对话",note:"笔记",attachment:"附件"};
const stateLabels={favorite:"已收藏",unread:"待读",read:"已读"};
const state={query:"",category:"",type:"",stateFilter:"",review:false,page:1,stats:null};
const $=selector=>document.querySelector(selector);
async function api(path,options={}){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function safeExcerpt(value=""){return escapeHtml(value).replaceAll("&lt;mark&gt;","<mark>").replaceAll("&lt;/mark&gt;","</mark>")}
function formatSize(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024**2).toFixed(1)} MB`}
function formatDate(value){return value?value.slice(0,10):"日期未知"}
function renderFilters(){
  const render=(mapping,counts,selected,key)=>Object.entries(mapping).map(([value,label])=>`<button class="filter-option ${selected===value?"active":""}" data-filter="${key}" data-value="${value}"><span>${label}</span><small>${counts?.[value]||0}</small></button>`).join("");
  $("#categoryFilters").innerHTML=render(categories,state.stats.categories,state.category,"category");$("#typeFilters").innerHTML=render(types,state.stats.types,state.type,"type");
  $("#stateFilters").innerHTML=render(stateLabels,{favorite:state.stats.favorites,read:state.stats.read,unread:state.stats.total-state.stats.read},state.stateFilter,"stateFilter");
  document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{state[button.dataset.filter]=state[button.dataset.filter]===button.dataset.value?"":button.dataset.value;state.page=1;renderFilters();loadResults()}))
}
function renderResults(data){
  $("#resultCount").textContent=data.total.toLocaleString("zh-CN");$("#resultContext").textContent=state.query?`正文检索：“${state.query}”`:"按保存时间浏览全部内容";
  $("#results").innerHTML=data.items.length?data.items.map(item=>`<article class="archive-row"><div class="spine" aria-hidden="true"></div><div class="row-main"><div class="row-meta"><span class="category">${categories[item.primary_category]||item.primary_category}</span><span>·</span><span>${types[item.asset_type]||item.asset_type}</span>${item.is_favorite?`<span class="state-mark">★ 收藏</span>`:""}${item.read_status==="read"?`<span class="state-mark">✓ 已读</span>`:""}${item.classification_source==="auto-v2"?`<span class="confidence">建议 ${Math.round((item.classification_confidence||0)*100)}%</span>`:""}</div><h3><button data-asset="${item.asset_id}">${escapeHtml(item.title_clean||"无标题网页")}</button></h3><p class="excerpt">${safeExcerpt(item.excerpt||"该档案尚无可展示的正文摘要。")}</p></div><div class="row-side"><div>${formatDate(item.saved_at)} · ${formatSize(item.size_bytes)}</div><div>${escapeHtml(item.source_domain||"本地内容")}</div>${item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">查看原网址 ↗</a>`:""}</div></article>`).join(""):`<div class="empty">没有匹配结果。尝试减少关键词，或清空分类筛选。</div>`;
  document.querySelectorAll("[data-asset]").forEach(button=>button.addEventListener("click",()=>openAsset(button.dataset.asset)));renderPagination(data.page,data.pages)
}
function renderPagination(current,pages){if(pages<=1){$("#pagination").innerHTML="";return}const start=Math.max(1,current-2),end=Math.min(pages,current+2),values=[];for(let page=start;page<=end;page++)values.push(page);$("#pagination").innerHTML=values.map(page=>`<button class="${page===current?"active":""}" data-page="${page}">${page}</button>`).join("");document.querySelectorAll("[data-page]").forEach(button=>button.addEventListener("click",()=>{state.page=Number(button.dataset.page);loadResults();window.scrollTo({top:$(".workspace").offsetTop-20,behavior:"smooth"})}))}
async function loadResults(){$("#results").innerHTML=`<div class="loading">正在翻阅本地档案…</div>`;const params=new URLSearchParams({q:state.query,category:state.category,type:state.type,state:state.stateFilter,review:state.review?"1":"0",page:state.page,limit:30});try{renderResults(await api(`/api/search?${params}`))}catch(error){$("#results").innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`}}
async function openAsset(assetId){
  const item=await api(`/api/assets/${assetId}`);$("#assetDetail").innerHTML=`<section class="detail"><div class="detail-kicker">${types[item.asset_type]||item.asset_type} / ${item.asset_id}</div><h2>${escapeHtml(item.title_clean||"无标题网页")}</h2><div class="detail-actions"><button id="favoriteToggle" class="${item.is_favorite?"active":""}">${item.is_favorite?"★ 已收藏":"☆ 收藏"}</button><button id="readToggle" class="${item.read_status==="read"?"active":""}">${item.read_status==="read"?"✓ 已读":"○ 标为已读"}</button></div><dl class="detail-grid"><dt>保存日期</dt><dd>${escapeHtml(item.saved_at||"未知")}</dd><dt>来源域名</dt><dd>${escapeHtml(item.source_domain||"未知")}</dd><dt>本地路径</dt><dd>${escapeHtml(item.original_path)}</dd><dt>原始网址</dt><dd>${item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">${escapeHtml(item.source_url)}</a>`:"未记录"}</dd><dt>分类来源</dt><dd>${item.classification_source==="auto-v2"?`自动建议 · ${Math.round((item.classification_confidence||0)*100)}%`:(item.classification_source==="manual"?"人工确认":"已确认分类")}</dd><dt>分类依据</dt><dd>${escapeHtml(item.classification_reason||"未记录")}</dd></dl><div class="edit-form"><select id="detailCategory" aria-label="主分类">${Object.entries(categories).map(([value,label])=>`<option value="${value}" ${item.primary_category===value?"selected":""}>${label}</option>`).join("")}</select><button id="saveAsset">保存档案状态</button><input id="detailTags" value="${escapeHtml(item.tags.join(", "))}" placeholder="标签用逗号分隔"><label class="note-label">个人备注<textarea id="personalNote" placeholder="记录为什么保存、后续要做什么">${escapeHtml(item.personal_note||"")}</textarea></label></div><div class="body-preview">${escapeHtml((item.body_text||"暂无正文").slice(0,6000))}</div></section>`;
  let favorite=Boolean(item.is_favorite),readStatus=item.read_status;
  $("#favoriteToggle").addEventListener("click",()=>{favorite=!favorite;$("#favoriteToggle").classList.toggle("active",favorite);$("#favoriteToggle").textContent=favorite?"★ 已收藏":"☆ 收藏"});
  $("#readToggle").addEventListener("click",()=>{readStatus=readStatus==="read"?"unread":"read";$("#readToggle").classList.toggle("active",readStatus==="read");$("#readToggle").textContent=readStatus==="read"?"✓ 已读":"○ 标为已读"});
  $("#assetDialog").showModal();$("#saveAsset").addEventListener("click",async()=>{const payload={primary_category:$("#detailCategory").value,tags:$("#detailTags").value.split(/[,，]/),is_favorite:favorite,read_status:readStatus,personal_note:$("#personalNote").value};await api(`/api/assets/${assetId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});$("#assetDialog").close();showToast("档案状态已保存");await refreshStats();await loadResults()})
}
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
async function refreshStats(){state.stats=await api("/api/stats");$("#archiveStatus").textContent=`${state.stats.total} 份档案 / ${state.stats.indexed} 份正文已索引 / 忽略 ${state.stats.ignored} 个系统文件`;$("#reviewCount").textContent=state.stats.review;$("#reviewFilter").classList.toggle("active",state.review);renderFilters()}
$("#searchForm").addEventListener("submit",event=>{event.preventDefault();state.query=$("#searchInput").value.trim();state.page=1;loadResults()});document.querySelectorAll("[data-query]").forEach(button=>button.addEventListener("click",()=>{$("#searchInput").value=button.dataset.query;state.query=button.dataset.query;state.page=1;loadResults()}));$("#reviewFilter").addEventListener("click",()=>{state.review=!state.review;state.page=1;$("#reviewFilter").classList.toggle("active",state.review);loadResults()});$("#clearFilters").addEventListener("click",()=>{state.query=state.category=state.type=state.stateFilter="";state.review=false;state.page=1;$("#searchInput").value="";$("#reviewFilter").classList.remove("active");renderFilters();loadResults()});refreshStats().then(loadResults).catch(error=>{$("#archiveStatus").textContent=error.message});
