const categories={technology:"开发技术",ai:"人工智能","career-work":"职场工作","finance-business":"金融商业",life:"生活","society-culture":"社会人文","productivity-tools":"效率工具",uncategorized:"暂未分类"};
const types={"web-html":"HTML 网页","web-mhtml":"MHTML 网页","video-page":"视频页面","search-page":"搜索页面","ai-chat":"AI 对话",note:"笔记",attachment:"附件"};
const stateLabels={favorite:"已收藏",unread:"待读",read:"已读"};
const requiredApiVersion=9;
const issueLabels={duplicate:"重复内容",parse_error:"清单扫描失败",extraction_error:"正文提取失败",missing:"源文件缺失"};
const state={query:"",category:"",type:"",stateFilter:"",review:false,issue:"",tag:"",domain:"",dateFrom:"",dateTo:"",sort:"saved_desc",page:1,stats:null};
const $=selector=>document.querySelector(selector);
async function api(path,options={}){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function safeExcerpt(value=""){return escapeHtml(value).replaceAll("&lt;mark&gt;","<mark>").replaceAll("&lt;/mark&gt;","</mark>")}
function formatSize(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024**2).toFixed(1)} MB`}
function formatDate(value){return value?value.slice(0,10):"日期未知"}
function renderFilters(){
  const render=(mapping,counts,selected,key)=>Object.entries(mapping).map(([value,label])=>`<button class="filter-option ${selected===value?"active":""}" data-filter="${key}" data-value="${value}"><span>${label}</span><small>${counts?.[value]||0}</small></button>`).join("");
  $("#categoryFilters").innerHTML=render(categories,state.stats.categories,state.category,"category");$("#typeFilters").innerHTML=render(types,state.stats.types,state.type,"type");
  $("#stateFilters").innerHTML=render(stateLabels,{favorite:state.stats.favorites,read:state.stats.read,unread:state.stats.total-state.stats.read},state.stateFilter,"stateFilter");
  $("#tagFilters").innerHTML=state.stats.tags.length?state.stats.tags.slice(0,12).map(item=>`<button class="tag-option ${state.tag===item.tag?"active":""}" data-filter="tag" data-value="${escapeHtml(item.tag)}">${escapeHtml(item.tag)} <small>${item.count}</small></button>`).join(""):`<span class="empty-tags">添加自定义标签后会显示在这里</span>`;
  const maintenance=state.stats.maintenance;const issueCounts={duplicate:maintenance.duplicate_assets,parse_error:maintenance.parse_errors,extraction_error:maintenance.extraction_errors,missing:maintenance.missing};
  $("#maintenanceFilters").innerHTML=Object.entries(issueLabels).map(([value,label])=>`<button class="maintenance-option ${state.issue===value?"active":""}" data-filter="issue" data-value="${value}"><span>${label}</span><strong>${issueCounts[value]}</strong></button>`).join("");
  const issueTotal=maintenance.duplicate_assets+maintenance.parse_errors+maintenance.extraction_errors+maintenance.missing;$("#healthStamp").textContent=issueTotal?`${issueTotal} 项待处理`:"索引健康";$("#healthStamp").classList.toggle("attention",Boolean(issueTotal));
  document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{state[button.dataset.filter]=state[button.dataset.filter]===button.dataset.value?"":button.dataset.value;state.page=1;renderFilters();loadResults()}))
}
function renderCriteria(){
  const tags=[];
  if(state.query)tags.push(["query",`检索：${state.query}`]);
  if(state.category)tags.push(["category",`分类：${categories[state.category]}`]);
  if(state.type)tags.push(["type",`类型：${types[state.type]}`]);
  if(state.stateFilter)tags.push(["stateFilter",`状态：${stateLabels[state.stateFilter]}`]);
  if(state.domain)tags.push(["domain",`来源：${state.domain}`]);
  if(state.dateFrom)tags.push(["dateFrom",`从 ${state.dateFrom}`]);
  if(state.dateTo)tags.push(["dateTo",`到 ${state.dateTo}`]);
  if(state.issue)tags.push(["issue",`维护：${issueLabels[state.issue]}`]);
  if(state.tag)tags.push(["tag",`索引签：${state.tag}`]);
  $("#activeCriteria").innerHTML=tags.map(([key,label])=>`<button class="criteria-tag" data-criterion="${key}">${escapeHtml(label)}</button>`).join("");
  document.querySelectorAll("[data-criterion]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.criterion;state[key]="";if(key==="query")$("#searchInput").value="";if(key==="domain")$("#domainFilter").value="";if(key==="dateFrom")$("#dateFrom").value="";if(key==="dateTo")$("#dateTo").value="";state.page=1;renderFilters();loadResults()}));
}
function renderResults(data){
  $("#resultCount").textContent=data.total.toLocaleString("zh-CN");const orderLabels={saved_desc:"最近保存优先",saved_asc:"最早保存优先",modified_desc:"最近修改优先",size_desc:"大文件优先",relevance:"相关度优先"};$("#resultContext").textContent=state.query?`正文检索 · ${orderLabels[state.sort]}`:orderLabels[state.sort];
  $("#results").innerHTML=data.items.length?data.items.map(item=>{const issueMark=item.file_status==="missing"?"源文件缺失":item.extraction_status==="error"?"正文提取失败":item.parse_status==="error"?"清单扫描失败":item.duplicate_group?"重复内容":"";const issueText=item.extraction_error||item.error_message;return `<article class="archive-row ${issueMark?"has-issue":""}"><div class="spine" aria-hidden="true"></div><div class="row-main"><div class="row-meta"><span class="category">${categories[item.primary_category]||item.primary_category}</span><span>·</span><span>${types[item.asset_type]||item.asset_type}</span>${issueMark?`<span class="issue-mark">${issueMark}</span>`:""}${item.is_favorite?`<span class="state-mark">★ 收藏</span>`:""}${item.read_status==="read"?`<span class="state-mark">✓ 已读</span>`:""}${item.classification_source==="auto-v2"?`<span class="confidence">建议 ${Math.round((item.classification_confidence||0)*100)}%</span>`:""}</div><h3><button data-asset="${item.asset_id}">${escapeHtml(item.title_clean||"无标题网页")}</button></h3><p class="excerpt">${safeExcerpt(issueText||item.excerpt||"该档案尚无可展示的正文摘要。")}</p></div><div class="row-side"><div>${formatDate(item.saved_at)} · ${formatSize(item.size_bytes)}</div><div>${escapeHtml(item.source_domain||"本地内容")}</div>${item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">查看原网址 ↗</a>`:""}</div></article>`}).join(""):`<div class="empty">${state.issue?`${issueLabels[state.issue]}队列为空，当前无需处理。`:"没有匹配结果。尝试减少关键词，或清空分类筛选。"}</div>`;
  document.querySelectorAll("[data-asset]").forEach(button=>button.addEventListener("click",()=>openAsset(button.dataset.asset)));renderPagination(data.page,data.pages)
}
function renderPagination(current,pages){if(pages<=1){$("#pagination").innerHTML="";return}const start=Math.max(1,current-2),end=Math.min(pages,current+2),values=[];for(let page=start;page<=end;page++)values.push(page);$("#pagination").innerHTML=values.map(page=>`<button class="${page===current?"active":""}" data-page="${page}">${page}</button>`).join("");document.querySelectorAll("[data-page]").forEach(button=>button.addEventListener("click",()=>{state.page=Number(button.dataset.page);loadResults();window.scrollTo({top:$(".workspace").offsetTop-20,behavior:"smooth"})}))}
async function loadResults(){$("#results").innerHTML=`<div class="loading">正在翻阅本地档案…</div>`;renderCriteria();const params=new URLSearchParams({q:state.query,category:state.category,type:state.type,state:state.stateFilter,review:state.review?"1":"0",issue:state.issue,tag:state.tag,domain:state.domain,from:state.dateFrom,to:state.dateTo,sort:state.sort,page:state.page,limit:30});try{renderResults(await api(`/api/search?${params}`))}catch(error){$("#results").innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`}}
async function openAsset(assetId){
  const item=await api(`/api/assets/${assetId}`);const canPreview=["html","htm"].includes((item.extension||"").toLowerCase())&&item.file_status!=="missing";const maintenanceNote=item.file_status==="missing"?"源文件当前不存在":item.extraction_status==="error"?item.extraction_error:item.parse_status==="error"?item.error_message:item.duplicate_group?`重复组 ${item.duplicate_group}`:"索引状态正常";$("#assetDetail").innerHTML=`<section class="detail"><div class="detail-kicker">${types[item.asset_type]||item.asset_type} / ${item.asset_id}</div><h2>${escapeHtml(item.title_clean||"无标题网页")}</h2><div class="detail-actions">${canPreview?`<a class="primary-action" href="/preview/${item.asset_id}" target="_blank" rel="noreferrer">安全预览 ↗</a>`:""}<button id="systemOpen" ${item.file_status==="missing"?"disabled":""}>系统打开</button><button id="revealFile" ${item.file_status==="missing"?"disabled":""}>在 Finder 中显示</button><button id="favoriteToggle" class="${item.is_favorite?"active":""}">${item.is_favorite?"★ 已收藏":"☆ 收藏"}</button><button id="readToggle" class="${item.read_status==="read"?"active":""}">${item.read_status==="read"?"✓ 已读":"○ 标为已读"}</button></div><dl class="detail-grid"><dt>保存日期</dt><dd>${escapeHtml(item.saved_at||"未知")}</dd><dt>来源域名</dt><dd>${escapeHtml(item.source_domain||"未知")}</dd><dt>本地路径</dt><dd>${escapeHtml(item.original_path)}</dd><dt>原始网址</dt><dd>${item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">${escapeHtml(item.source_url)}</a>`:"未记录"}</dd><dt>维护状态</dt><dd>${escapeHtml(maintenanceNote||"未知错误")}</dd><dt>分类来源</dt><dd>${item.classification_source==="auto-v2"?`自动建议 · ${Math.round((item.classification_confidence||0)*100)}%`:(item.classification_source==="manual"?"人工确认":"已确认分类")}</dd><dt>分类依据</dt><dd>${escapeHtml(item.classification_reason||"未记录")}</dd></dl><div class="edit-form"><select id="detailCategory" aria-label="主分类">${Object.entries(categories).map(([value,label])=>`<option value="${value}" ${item.primary_category===value?"selected":""}>${label}</option>`).join("")}</select><button id="saveAsset">保存档案状态</button><label class="metadata-field">档案标题<input id="detailTitle" value="${escapeHtml(item.title_clean||"")}" maxlength="1000"></label><label class="metadata-field">原始网址<input id="detailSourceUrl" type="url" value="${escapeHtml(item.source_url||"")}" placeholder="https://example.com/article"></label><input id="detailTags" value="${escapeHtml(item.tags.join(", "))}" placeholder="标签用逗号分隔"><label class="note-label">个人备注<textarea id="personalNote" placeholder="记录为什么保存、后续要做什么">${escapeHtml(item.personal_note||"")}</textarea></label></div><div class="body-preview">${escapeHtml((item.body_text||"暂无正文").slice(0,6000))}</div></section>`;
  let favorite=Boolean(item.is_favorite),readStatus=item.read_status;
  $("#favoriteToggle").addEventListener("click",()=>{favorite=!favorite;$("#favoriteToggle").classList.toggle("active",favorite);$("#favoriteToggle").textContent=favorite?"★ 已收藏":"☆ 收藏"});
  $("#readToggle").addEventListener("click",()=>{readStatus=readStatus==="read"?"unread":"read";$("#readToggle").classList.toggle("active",readStatus==="read");$("#readToggle").textContent=readStatus==="read"?"✓ 已读":"○ 标为已读"});
  if(item.file_status!=="missing")$("#systemOpen").addEventListener("click",async()=>{try{await api(`/api/assets/${assetId}/open`,{method:"POST"});showToast("已交给系统默认应用打开")}catch(error){showToast(error.message)}});
  if(item.file_status!=="missing")$("#revealFile").addEventListener("click",async()=>{try{await api(`/api/assets/${assetId}/reveal`,{method:"POST"});showToast("已在 Finder 中定位原文件")}catch(error){showToast(error.message)}});
  $("#assetDialog").showModal();$("#saveAsset").addEventListener("click",async()=>{const payload={primary_category:$("#detailCategory").value,tags:$("#detailTags").value.split(/[,，]/),is_favorite:favorite,read_status:readStatus,personal_note:$("#personalNote").value,title_clean:$("#detailTitle").value,source_url:$("#detailSourceUrl").value};try{const saved=await api(`/api/assets/${assetId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(saved.is_favorite!==payload.is_favorite||saved.read_status!==payload.read_status||saved.personal_note!==payload.personal_note||saved.title_clean!==payload.title_clean.trim())throw new Error("服务仍在运行旧版本，请在终端按 Ctrl+C 后重新启动 python3 app.py");$("#assetDialog").close();showToast("档案状态已保存");await refreshStats();await loadResults()}catch(error){showToast(error.message)}})
}
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
async function refreshStats(){state.stats=await api("/api/stats");if((state.stats.api_version||0)<requiredApiVersion)throw new Error("服务版本过旧：请在终端按 Ctrl+C 后重新启动 python3 app.py");const missing=state.stats.missing?` / ${state.stats.missing} 份源文件缺失`:"";$("#archiveStatus").textContent=`${state.stats.total} 份档案 / ${state.stats.indexed} 份正文已索引 / 忽略 ${state.stats.ignored} 个系统文件${missing} · v${state.stats.app_version}`;$("#reviewCount").textContent=state.stats.review;$("#reviewFilter").classList.toggle("active",state.review);$("#domainFilter").innerHTML=`<option value="">全部来源</option>`+state.stats.domains.map(item=>`<option value="${escapeHtml(item.domain)}">${escapeHtml(item.domain)} (${item.count})</option>`).join("");renderFilters()}
$("#runScan").addEventListener("click",async()=>{const button=$("#runScan");button.disabled=true;button.querySelector("span").textContent="正在同步…";try{const result=await api("/api/maintenance/scan",{method:"POST"});showToast(`同步完成：新增 ${result.added||0}，更新 ${result.updated||0}，移动 ${result.moved||0}，缺失 ${result.newly_missing||0}`);await refreshStats();await loadResults()}catch(error){showToast(error.message)}finally{button.disabled=false;button.querySelector("span").textContent="同步归档"}});
$("#exportData").addEventListener("click",()=>{const link=document.createElement("a");link.href="/api/data/export";link.download="web-archive-overrides.json";link.click();showToast("人工数据导出已开始")});
$("#importData").addEventListener("click",()=>$("#importFile").click());$("#importFile").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;const button=$("#importData");button.disabled=true;try{const result=await api("/api/data/import",{method:"POST",headers:{"Content-Type":"application/json"},body:await file.text()});showToast(`已合并 ${result.imported} 条，跳过 ${result.skipped} 条`);await refreshStats();await loadResults()}catch(error){showToast(error.message)}finally{button.disabled=false;event.target.value=""}});
$("#backupData").addEventListener("click",async()=>{const button=$("#backupData");button.disabled=true;try{const result=await api("/api/data/backup",{method:"POST"});showToast(`本地快照 ${result.backup_id} 已创建`)}catch(error){showToast(error.message)}finally{button.disabled=false}});
$("#checkHealth").addEventListener("click",async()=>{const button=$("#checkHealth");button.disabled=true;try{const result=await api("/api/health");showToast(result.status==="healthy"?`索引健康：${result.assets} 条资产，${result.fts_documents} 份全文索引`:`索引需要检查：${result.integrity_check}`)}catch(error){showToast(error.message)}finally{button.disabled=false}});
$("#searchForm").addEventListener("submit",event=>{event.preventDefault();state.query=$("#searchInput").value.trim();state.sort=state.query?"relevance":"saved_desc";$("#sortOrder").value=state.sort;state.page=1;loadResults()});document.querySelectorAll("[data-query]").forEach(button=>button.addEventListener("click",()=>{$("#searchInput").value=button.dataset.query;state.query=button.dataset.query;state.sort="relevance";$("#sortOrder").value=state.sort;state.page=1;loadResults()}));$("#catalogControls").addEventListener("submit",event=>{event.preventDefault();state.dateFrom=$("#dateFrom").value;state.dateTo=$("#dateTo").value;state.domain=$("#domainFilter").value;state.sort=$("#sortOrder").value;if(!state.query&&state.sort==="relevance"){state.sort="saved_desc";$("#sortOrder").value=state.sort}state.page=1;loadResults()});$("#reviewFilter").addEventListener("click",()=>{state.review=!state.review;state.page=1;$("#reviewFilter").classList.toggle("active",state.review);loadResults()});$("#clearFilters").addEventListener("click",()=>{state.query=state.category=state.type=state.stateFilter=state.domain=state.dateFrom=state.dateTo=state.issue=state.tag="";state.sort="saved_desc";state.review=false;state.page=1;$("#searchInput").value=$("#dateFrom").value=$("#dateTo").value=$("#domainFilter").value="";$("#sortOrder").value=state.sort;$("#reviewFilter").classList.remove("active");renderFilters();loadResults()});refreshStats().then(loadResults).catch(error=>{$("#archiveStatus").textContent=error.message});
